### ISSUE TITLE
Input no longer works as before

### ISSUE THREAD

**Issue by gchiu** [hostilefork/replpad-js#58] opened 2019-04-15 08:25 UTC
>> 	input
‌fail() @ ../src/core/a-lib.c 727
‌** Error: JavaScript error not in rebPromise()! (TBD: extract string here)
** Where: main
** Near: []

Input doesn't wait for input anymore

>> ‌rebol/build
== 14-Apr-2019/20:35:47+0:00

>> 	rebol/commit
== "4709cd43bf131eff85f18e6a8273ccf5f21f5cb0"

**Comment by gchiu** [comment] 2019-04-17 05:27
Week Ending (20-Apr-2019): 

is the prompt but now it looks like

Week Ending (20-
Apr-2019):

**Comment by hostilefork** [comment] 2019-04-22 13:43
This seems to be addressed, but more generally the issue of these regressions is intended to be addressed by the interactivity test:

https://github.com/hostilefork/replpad-js/pull/62

If you notice problems, then adding to the test (hopefully) helps keep them from happening again.

**Closed by hostilefork** 2019-04-22 13:43 UTC

**Comment by IngoHohmann** [comment] 2019-04-29 20:51
Chrome on android,
the prompt is displayed ok, but text input is displayed in a one character wide column, which is all the horizontal space, that is left.
